const extendedGtfsRouteTypes = [
  { c: 0, d: "Tram, Streetcar, Light rail" },
  { c: 1, d: "Subway, Metro" },
  { c: 2, d: "Rail" },
  { c: 3, d: "Bus" },
  { c: 4, d: "Ferry" },
  { c: 5, d: "Cable tram" },
  {
    c: 6,
    d: "Aerial lift, suspended cable car (e.g., gondola lift, aerial tramway)",
  },
  { c: 7, d: "Funicular" },
  { c: 11, d: "Trolleybus" },
  { c: 12, d: "Monorail" },
  { c: 100, d: "Railway Service" },
  { c: 101, d: "High Speed Rail Service" },
  { c: 102, d: "Long Distance Trains" },
  { c: 103, d: "Inter Regional Rail Service" },
  { c: 104, d: "Car Transport Rail Service" },
  { c: 105, d: "Sleeper Rail Service" },
  { c: 106, d: "Regional Rail Service" },
  { c: 107, d: "Tourist Railway Service" },
  { c: 108, d: "Rail Shuttle (Within Complex)" },
  { c: 109, d: "Suburban Railway" },
  { c: 110, d: "Replacement Rail Service" },
  { c: 111, d: "Special Rail Service" },
  { c: 112, d: "Lorry Transport Rail Service" },
  { c: 113, d: "All Rail Services" },
  { c: 114, d: "Cross-Country Rail Service" },
  { c: 115, d: "Vehicle Transport Rail Service" },
  { c: 116, d: "Rack and Pinion Railway" },
  { c: 117, d: "Additional Rail Service" },
  { c: 200, d: "Coach Service" },
  { c: 201, d: "International Coach Service" },
  { c: 202, d: "National Coach Service" },
  { c: 203, d: "Shuttle Coach Service" },
  { c: 204, d: "Regional Coach Service" },
  { c: 205, d: "Special Coach Service" },
  { c: 206, d: "Sightseeing Coach Service" },
  { c: 207, d: "Tourist Coach Service" },
  { c: 208, d: "Commuter Coach Service" },
  { c: 209, d: "All Coach Services" },
  { c: 400, d: "Urban Railway Service" },
  { c: 401, d: "Metro Service" },
  { c: 402, d: "Underground Service" },
  { c: 403, d: "Urban Railway Service" },
  { c: 404, d: "All Urban Railway Services" },
  { c: 405, d: "Monorail" },
  { c: 700, d: "Bus Service" },
  { c: 701, d: "Regional Bus Service" },
  { c: 702, d: "Express Bus Service" },
  { c: 703, d: "Stopping Bus Service" },
  { c: 704, d: "Local Bus Service" },
  { c: 705, d: "Night Bus Service" },
  { c: 706, d: "Post Bus Service" },
  { c: 707, d: "Special Needs Bus" },
  { c: 708, d: "Mobility Bus Service" },
  { c: 709, d: "Mobility Bus for Registered Disabled" },
  { c: 710, d: "Sightseeing Bus" },
  { c: 711, d: "Shuttle Bus" },
  { c: 712, d: "School Bus" },
  { c: 713, d: "School and Public Service Bus" },
  { c: 714, d: "Rail Replacement Bus Service" },
  { c: 715, d: "Demand and Response Bus Service" },
  { c: 716, d: "All Bus Services" },
  { c: 800, d: "Trolleybus Service" },
  { c: 900, d: "Tram Service" },
  { c: 901, d: "City Tram Service" },
  { c: 902, d: "Local Tram Service" },
  { c: 903, d: "Regional Tram Service" },
  { c: 904, d: "Sightseeing Tram Service" },
  { c: 905, d: "Shuttle Tram Service" },
  { c: 906, d: "All Tram Services" },
  { c: 1000, d: "Water Transport Service" },
  { c: 1100, d: "Air Service" },
  { c: 1200, d: "Ferry Service" },
  { c: 1300, d: "Aerial Lift Service" },
  { c: 1301, d: "Telecabin Service" },
  { c: 1302, d: "Cable Car Service" },
  { c: 1303, d: "Elevator Service" },
  { c: 1304, d: "Chair Lift Service" },
  { c: 1305, d: "Drag Lift Service" },
  { c: 1306, d: "Small Telecabin Service" },
  { c: 1307, d: "All Telecabin Services" },
  { c: 1400, d: "Funicular Service" },
  { c: 1500, d: "Taxi Service" },
  { c: 1501, d: "Communal Taxi Service" },
  { c: 1502, d: "Water Taxi Service" },
  { c: 1503, d: "Rail Taxi Service" },
  { c: 1504, d: "Bike Taxi Service" },
  { c: 1505, d: "Licensed Taxi Service" },
  { c: 1506, d: "Private Hire Service Vehicle" },
  { c: 1507, d: "All Taxi Services" },
  { c: 1700, d: "Miscellaneous Service" },
  { c: 1702, d: "Horse-drawn Carriage" },
];

export { extendedGtfsRouteTypes };
